name: Deploy to Render

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama principal de tu repositorio si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image
        run: docker pull docker.pkg.github.com/elbacapt/rot/rot-sprint5-1-java:latest

      - name: Deploy to Render
        env:
          RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
          RENDER_PASSWORD: ${{ secrets.RENDER_PASSWORD }}
        run: |
          docker tag docker.pkg.github.com/elbacapt/rot/rot-sprint5-1-java:latest registry.render.com/rot/rot-sprint5-1-java:latest
          docker push registry.render.com/rot/rot-sprint5-1-java:latest
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $RENDER_EMAIL:$RENDER_PASSWORD" -d '{}' https://api.render.com/v1/services/rot/redeploy
